### ISSUE TITLE
ProtoObject.ToString() truncates the message

### ISSUE THREAD

**Issue by ErrorEater** [ocoanet/ProtoUntyped#3]
The parsed object list looks fine, but ToString() truncates at some point.
Can you fix the issue and release a new package please.

Truncated message:
```
message {
- 1 = message {
    - 1 = message {
        - 1 = message {
            - 1 = 1
            - 3 = 10
            - 4 = 5
            }
        - 2 = message {
            - 2 = 5
            }
        - 3 = message {
            - 1 = 1
            - 3 = 10
            - 4 = 5
            }
        - 4 = message {
            - 1 = 1
            - 3 = 10
            - 4 = 5
            }
        - 5 = message {
            - 1 = 1
            - 3 = 10
            - 4 = 5
            - 5 = 10
            }
        - 6 = message {
            - 1 = 1
            - 3 = 10
            - 4 = 5
            - 5 = 10
            }
        }
    - 2 = message {
        - 1 = array [
            - 0 = message {
                - 1 = 10000
                - 2 = 5
                - 4 = "

```

Base 64 encoded original message:
[message_base64.txt](https://github.com/ocoanet/ProtoUntyped/files/11522187/message_base64.txt)

**Comment by ocoanet** [comment]
Wow, that's quite a large message, I might use it as a reference for performance tests :)

I tried to reproduce your issue. The output string is not really truncated, but it contains the null character, which probably causes your text to be truncated when printed.

It suspect that a few byte arrays are interpreted as strings here. I think I will change the default behavior to identify byte arrays with null characters are byte arrays instead of string.

You can probably temporary work around this problem using the string validator callback:

```cs
ProtoObject.Decode(bytes, new ProtoDecodeOptions { StringValidator = s => s.All(c => c != 0) });
```

I hope this helps.

**Comment by ocoanet** [comment]
Can you confirm that the problematic member (` 4 = "����`) is supposed to be a byte array?

**Comment by ErrorEater** [comment]
> Can you confirm that the problematic member (` 4 = "����`) is supposed to be a byte array?

The "TextBox" control in WinForms doesn't display the '\0' (null) char. That's why I see truncated value.

I really don't know what's the data type of the problematic member, that's why I'm using your code to understand it. :) But I think nobody can send a string value with null character, it has to be a byte array.

Can you also format byte arrays not Base64 Encoded but Hex Encoded inside brackets "[]" to quickly understand that it's an array. (Also valid for the fix you made to my previous issue.)

Hex Formatting:
```
var bs = new byte[] { 15, 25, 0, 180 };
var ss = $"[{string.Join(" ", bs.Select(b => b.ToString("X2")))}]";
```

**Comment by ocoanet** [comment]
I decided to keep base64 as the default byte array format, but now you can override the formatting:

```cs
var s = protoObject.ToString(new CustomProtoFormatter());

public class CustomProtoFormatter : ProtoFormatter
{
    protected override void FormatByteArray(StringBuilder stringBuilder, int indentSize, byte[] array)
    {
        stringBuilder.AppendLine($"[{string.Join(" ", array.Select(b => b.ToString("X2")))}]");
    }
}
```

Also, byte arrays with low control characters as now treated as bytes instead of strings by default.
