### ISSUE TITLE
Field number and ordering

### ISSUE THREAD

**Issue by ErrorEater** [ocoanet/ProtoUntyped#5]
As show in the output below the 2nd item of the 1st object has its field numbers in wrong order. 6 is expected to come before 7.
Why this happens?

Message in Base64 (updated):
`Co4DCuACZW1semZERjhOak41U2tabGNFOUpRakk0T1ZkVmNuSTFRamhxTVVka2JWVmtkWGwzU0ZSMlh6Vk5kMk5PUldOWllVVnBia3B0TWpWd2RuVmtaelpRVEdzdFUxZEhkVkpwVTB0SVkwaDBVR1JzTm5FeU1YbFZOR1F0VWtsa1V6WllYM0J3T0VNeVJEQXhZMHhKTlRkU1ZIUTRRekI0WWpkdU9YRmFTa293YjFWQmVXUkdaMWhDVDB0RFJETlZNbTR4U1VGNlkxTjJSbFF6Y1dOZmQybGtRVkZJYVhrMGJtZHBOMUZUVTAxcE1IVkRlbWxPV0Y5Q1UzWndOekpWVkVSaVIyZ3lNV0prVUhWQlprOXpjV2czUXpjeVFWVkZZVGRXUVdsTGRHZFlRalpDUVZCeE1FTklkR2hHTkhOTlUzVmZZVmhwYlRSalVuVkhTbWwzZHpOR1VXUkRkamd3VGc9PRILODgxNTQ4MzU2MDAaEDFhOGMyZGVhNzA2ZGM3MGQiCjE2ODYyNjc3OTMQ1ober8gCIB06IDg0OTk2OTYwMjU4OWI3YjRmZjIxMzVmZTM4MWVkMmY3`

Output:
```
message {
- 1 = message {
    - 1 = "emlzfDF8NjN5SkZlcE9JQjI4OVdVcnI1QjhqMUdkbVVkdXl3SFR2XzVNd2NORWNZYUVpbkptMjVwdnVkZzZQTGstU1dHdVJpU0tIY0h0UGRsNnEyMXlVNGQtUklkUzZYX3BwOEMyRDAxY0xJNTdSVHQ4QzB4YjduOXFaSkowb1VBeWRGZ1hCT0tDRDNVMm4xSUF6Y1N2RlQzcWNfd2lkQVFIaXk0bmdpN1FTU01pMHVDemlOWF9CU3ZwNzJVVERiR2gyMWJkUHVBZk9zcWg3QzcyQVVFYTdWQWlLdGdYQjZCQVBxMENIdGhGNHNNU3VfYVhpbTRjUnVHSml3dzNGUWRDdjgwTg=="
    - 2 = message {
        - 7 = 56
        - 6 = 1.4000739925779533E-76
        }
    - 3 = "1a8c2dea706dc70d"
    - 4 = "1686267793"
    }
- 2 = 88146936662
- 4 = 29
- 7 = "849969602589b7b4ff2135fe381ed2f7"
}

```

**Comment by ocoanet** [comment]
Here is the output I get for the provided bytes:
```
message {
- 1 = message {
    - 1 = "emlzfDF8eVNZVlFQcTNkZkR2U3dhRkFvX3ZyeGNnM2dqQzd5SDRsX3VEVmUtREZsX2stRGdINnN2ZXIza09zOHhocld6amhENElKV3R4WWJsOGlEUzQ2UXlUSXdRT3RWMldzcjVrYi12dnlBM2NWQ0dHODhrWG9TTEJqN29UWVhBOE9CeGNfQWRCV0pxeXNiTkJFVzRtY2JlRUVBPT0="
    - 2 = message {
        - 6 = 1.1996598566964243E-71
        - 7 = 56
        }
    - 3 = "8c9a4f6b64f6f772"
    }
- 2 = 24
- 3 = "d8432fc109424c55a9e01bb2aaf65309"
}
```

Are you sure your output and bytes are correct?

I reviewed the library code and I do not think that ProtoUntyped changes the order of the fields. So you should get the fields in the order they appear in the binary format. If you use protobuf-net to serialize your messages, your output is quite suspicious, because I think that protobuf-net orders the members by tag values, so it probably suggests an issue in ProtoUntyped.

**Comment by ErrorEater** [comment]
I pasted the wrong message and now updated it on my first message. The output ordering is still wrong. Please check the updated Base64 message above.
The message is what I receive from a HTTP request, I don't manipulate it with protobuf-net.

![image](https://github.com/ocoanet/ProtoUntyped/assets/8914034/7e6e5b32-ccb5-419e-91ef-c1cb1e34f2c0)

**Comment by ocoanet** [comment]
I can confirm that the wire format field order is preserved by ProtoUntyped. In your example, the record for field "7" is before the record for field "6".

I do not think that ProtoUntyped should reorder the fields automatically. However, I can easily add a `SortMembers` method on `ProtoObject` or an option to sort fields while decoding.

**Comment by ocoanet** [comment]
Sorting fields is now supported in v3.
